version: '3'
services:
  server:
    image: piroyoung/lantern-server:latest-alpha
    container_name: lantern-server
    hostname: lantern-server
    ports:
      - "6380:6380"
      - "2112:2112"
    environment:
      - LANTERN_PORT=6380
      - LANTERN_FLUSH_INTERVAL=60
      - PROMETHEUS_PORT=2112

  gateway:
    image: piroyoung/lantern-gateway:latest-alpha
    container_name: lantern-gateway
    hostname: lantern-gateway
    depends_on:
      - server
    ports:
      - "8081:8081"
      - "2113:2112"
    environment:
      - LANTERN_HOST=lantern-server
      - LANTERN_PORT=6380
      - GATEWAY_PORT=8081
      - ALLOWED_ORIGIN=http://localhost:8080
      - PROMETHEUS_PORT=2112

  viewer:
    image: piroyoung/lantern-viewer:latest-alpha
    container_name: lantern-viewer
    hostname: lantern-viewer
    depends_on:
      - gateway
    ports:
      - "8080:8080"
    environment:
      - LANTERN_ENDPOINT=http://localhost:8081

  prometheus:
    image: bitnami/prometheus
    container_name: prometheus-server
    depends_on:
      - gateway
      - server
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
