global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "lantern-server:2112"
        labels:
          group: "lantern-server"

      - targets:
          - "lantern-gateway:2112"
        labels:
          group: "lantern-gateway"