// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: data.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Status int32

const (
	Status_OK                    Status = 0
	Status_INTERNAL_SERVER_ERROR Status = 1
	Status_INVALID_REQUEST       Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "INTERNAL_SERVER_ERROR",
		2: "INVALID_REQUEST",
	}
	Status_value = map[string]int32{
		"OK":                    0,
		"INTERNAL_SERVER_ERROR": 1,
		"INVALID_REQUEST":       2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_data_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_data_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

type Vertex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Expiration *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	// Types that are assignable to Value:
	//	*Vertex_Float64
	//	*Vertex_Float32
	//	*Vertex_Int32
	//	*Vertex_Int64
	//	*Vertex_Uint32
	//	*Vertex_Uint64
	//	*Vertex_Bool
	//	*Vertex_String_
	//	*Vertex_Bytes
	//	*Vertex_Timestamp
	//	*Vertex_Nil
	Value isVertex_Value `protobuf_oneof:"value"`
}

func (x *Vertex) Reset() {
	*x = Vertex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vertex) ProtoMessage() {}

func (x *Vertex) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vertex.ProtoReflect.Descriptor instead.
func (*Vertex) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *Vertex) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Vertex) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (m *Vertex) GetValue() isVertex_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Vertex) GetFloat64() float64 {
	if x, ok := x.GetValue().(*Vertex_Float64); ok {
		return x.Float64
	}
	return 0
}

func (x *Vertex) GetFloat32() float32 {
	if x, ok := x.GetValue().(*Vertex_Float32); ok {
		return x.Float32
	}
	return 0
}

func (x *Vertex) GetInt32() int32 {
	if x, ok := x.GetValue().(*Vertex_Int32); ok {
		return x.Int32
	}
	return 0
}

func (x *Vertex) GetInt64() int64 {
	if x, ok := x.GetValue().(*Vertex_Int64); ok {
		return x.Int64
	}
	return 0
}

func (x *Vertex) GetUint32() uint32 {
	if x, ok := x.GetValue().(*Vertex_Uint32); ok {
		return x.Uint32
	}
	return 0
}

func (x *Vertex) GetUint64() uint64 {
	if x, ok := x.GetValue().(*Vertex_Uint64); ok {
		return x.Uint64
	}
	return 0
}

func (x *Vertex) GetBool() bool {
	if x, ok := x.GetValue().(*Vertex_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *Vertex) GetString_() string {
	if x, ok := x.GetValue().(*Vertex_String_); ok {
		return x.String_
	}
	return ""
}

func (x *Vertex) GetBytes() []byte {
	if x, ok := x.GetValue().(*Vertex_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (x *Vertex) GetTimestamp() *timestamppb.Timestamp {
	if x, ok := x.GetValue().(*Vertex_Timestamp); ok {
		return x.Timestamp
	}
	return nil
}

func (x *Vertex) GetNil() bool {
	if x, ok := x.GetValue().(*Vertex_Nil); ok {
		return x.Nil
	}
	return false
}

type isVertex_Value interface {
	isVertex_Value()
}

type Vertex_Float64 struct {
	Float64 float64 `protobuf:"fixed64,10,opt,name=float64,proto3,oneof"`
}

type Vertex_Float32 struct {
	Float32 float32 `protobuf:"fixed32,11,opt,name=float32,proto3,oneof"`
}

type Vertex_Int32 struct {
	Int32 int32 `protobuf:"varint,12,opt,name=int32,proto3,oneof"`
}

type Vertex_Int64 struct {
	Int64 int64 `protobuf:"varint,13,opt,name=int64,proto3,oneof"`
}

type Vertex_Uint32 struct {
	Uint32 uint32 `protobuf:"varint,14,opt,name=uint32,proto3,oneof"`
}

type Vertex_Uint64 struct {
	Uint64 uint64 `protobuf:"varint,15,opt,name=uint64,proto3,oneof"`
}

type Vertex_Bool struct {
	Bool bool `protobuf:"varint,16,opt,name=bool,proto3,oneof"`
}

type Vertex_String_ struct {
	String_ string `protobuf:"bytes,17,opt,name=string,proto3,oneof"`
}

type Vertex_Bytes struct {
	Bytes []byte `protobuf:"bytes,18,opt,name=bytes,proto3,oneof"`
}

type Vertex_Timestamp struct {
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=timestamp,proto3,oneof"`
}

type Vertex_Nil struct {
	Nil bool `protobuf:"varint,30,opt,name=nil,proto3,oneof"`
}

func (*Vertex_Float64) isVertex_Value() {}

func (*Vertex_Float32) isVertex_Value() {}

func (*Vertex_Int32) isVertex_Value() {}

func (*Vertex_Int64) isVertex_Value() {}

func (*Vertex_Uint32) isVertex_Value() {}

func (*Vertex_Uint64) isVertex_Value() {}

func (*Vertex_Bool) isVertex_Value() {}

func (*Vertex_String_) isVertex_Value() {}

func (*Vertex_Bytes) isVertex_Value() {}

func (*Vertex_Timestamp) isVertex_Value() {}

func (*Vertex_Nil) isVertex_Value() {}

type Edge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tail       string                 `protobuf:"bytes,1,opt,name=tail,proto3" json:"tail,omitempty"`
	Head       string                 `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Weight     float32                `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Expiration *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (x *Edge) Reset() {
	*x = Edge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetTail() string {
	if x != nil {
		return x.Tail
	}
	return ""
}

func (x *Edge) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *Edge) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Edge) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type GraphStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VertexDegrees []*GraphStats_VertexDegree `protobuf:"bytes,1,rep,name=vertex_degrees,json=vertexDegrees,proto3" json:"vertex_degrees,omitempty"`
}

func (x *GraphStats) Reset() {
	*x = GraphStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphStats) ProtoMessage() {}

func (x *GraphStats) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphStats.ProtoReflect.Descriptor instead.
func (*GraphStats) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

func (x *GraphStats) GetVertexDegrees() []*GraphStats_VertexDegree {
	if x != nil {
		return x.VertexDegrees
	}
	return nil
}

type Graph struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vertices []*Vertex   `protobuf:"bytes,1,rep,name=vertices,proto3" json:"vertices,omitempty"`
	Edges    []*Edge     `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	Stats    *GraphStats `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *Graph) Reset() {
	*x = Graph{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{3}
}

func (x *Graph) GetVertices() []*Vertex {
	if x != nil {
		return x.Vertices
	}
	return nil
}

func (x *Graph) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *Graph) GetStats() *GraphStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type IlluminateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed      string  `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Step      uint32  `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	MinWeight float32 `protobuf:"fixed32,3,opt,name=min_weight,json=minWeight,proto3" json:"min_weight,omitempty"`
	MaxWeight float32 `protobuf:"fixed32,4,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
}

func (x *IlluminateRequest) Reset() {
	*x = IlluminateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IlluminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IlluminateRequest) ProtoMessage() {}

func (x *IlluminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IlluminateRequest.ProtoReflect.Descriptor instead.
func (*IlluminateRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{4}
}

func (x *IlluminateRequest) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *IlluminateRequest) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *IlluminateRequest) GetMinWeight() float32 {
	if x != nil {
		return x.MinWeight
	}
	return 0
}

func (x *IlluminateRequest) GetMaxWeight() float32 {
	if x != nil {
		return x.MaxWeight
	}
	return 0
}

type Keys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *Keys) Reset() {
	*x = Keys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keys) ProtoMessage() {}

func (x *Keys) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keys.ProtoReflect.Descriptor instead.
func (*Keys) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{5}
}

func (x *Keys) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type IlluminateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Graph  *Graph `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
}

func (x *IlluminateResponse) Reset() {
	*x = IlluminateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IlluminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IlluminateResponse) ProtoMessage() {}

func (x *IlluminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IlluminateResponse.ProtoReflect.Descriptor instead.
func (*IlluminateResponse) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{6}
}

func (x *IlluminateResponse) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *IlluminateResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type PutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{7}
}

func (x *PutResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type GraphStats_VertexDegree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	In  uint32 `protobuf:"varint,2,opt,name=in,proto3" json:"in,omitempty"`
	Out uint32 `protobuf:"varint,3,opt,name=out,proto3" json:"out,omitempty"`
}

func (x *GraphStats_VertexDegree) Reset() {
	*x = GraphStats_VertexDegree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphStats_VertexDegree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphStats_VertexDegree) ProtoMessage() {}

func (x *GraphStats_VertexDegree) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphStats_VertexDegree.ProtoReflect.Descriptor instead.
func (*GraphStats_VertexDegree) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GraphStats_VertexDegree) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GraphStats_VertexDegree) GetIn() uint32 {
	if x != nil {
		return x.In
	}
	return 0
}

func (x *GraphStats_VertexDegree) GetOut() uint32 {
	if x != nil {
		return x.Out
	}
	return 0
}

var File_data_proto protoreflect.FileDescriptor

var file_data_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x03,
	0x0a, 0x06, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3a, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x36,
	0x34, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x36, 0x34, 0x12, 0x1a, 0x0a, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x12, 0x16,
	0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x16, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x18,
	0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00,
	0x52, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x18, 0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74,
	0x36, 0x34, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x06, 0x75, 0x69, 0x6e, 0x74,
	0x36, 0x34, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x12, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x03, 0x6e, 0x69, 0x6c, 0x18, 0x1e, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x03, 0x6e, 0x69, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x04, 0x45, 0x64, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x3a, 0x0a, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x91, 0x01, 0x0a, 0x0a, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x74, 0x65,
	0x78, 0x5f, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x56, 0x65, 0x72,
	0x74, 0x65, 0x78, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x52, 0x0d, 0x76, 0x65, 0x72, 0x74, 0x65,
	0x78, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x73, 0x1a, 0x42, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x74,
	0x65, 0x78, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x22, 0x6c, 0x0a, 0x05,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x23, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78,
	0x52, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x05, 0x65, 0x64,
	0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x45, 0x64, 0x67, 0x65,
	0x52, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x79, 0x0a, 0x11, 0x49, 0x6c,
	0x6c, 0x75, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x65, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6d, 0x69, 0x6e,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79,
	0x73, 0x22, 0x53, 0x0a, 0x12, 0x49, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x05,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2e, 0x0a, 0x0b, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x40, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x4e, 0x54, 0x45,
	0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x52,
	0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x02, 0x32, 0xc7, 0x01, 0x0a, 0x07, 0x4c, 0x61, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x12, 0x37, 0x0a, 0x0a, 0x49, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x2e, 0x49, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x49, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x1c, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x12, 0x05, 0x2e, 0x4b, 0x65, 0x79,
	0x73, 0x1a, 0x06, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x22, 0x00, 0x12, 0x1d, 0x0a, 0x03, 0x50,
	0x75, 0x74, 0x12, 0x06, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x1a, 0x0c, 0x2e, 0x50, 0x75, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x09, 0x50, 0x75,
	0x74, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x12, 0x06, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x1a,
	0x0c, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x21, 0x0a, 0x07, 0x50, 0x75, 0x74, 0x45, 0x64, 0x67, 0x65, 0x12, 0x06, 0x2e, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x1a, 0x0c, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6c, 0x61, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x2d, 0x64, 0x62, 0x2f, 0x6c, 0x61, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData = file_data_proto_rawDesc
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_proto_rawDescData)
	})
	return file_data_proto_rawDescData
}

var file_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_data_proto_goTypes = []interface{}{
	(Status)(0),                     // 0: Status
	(*Vertex)(nil),                  // 1: Vertex
	(*Edge)(nil),                    // 2: Edge
	(*GraphStats)(nil),              // 3: GraphStats
	(*Graph)(nil),                   // 4: Graph
	(*IlluminateRequest)(nil),       // 5: IlluminateRequest
	(*Keys)(nil),                    // 6: Keys
	(*IlluminateResponse)(nil),      // 7: IlluminateResponse
	(*PutResponse)(nil),             // 8: PutResponse
	(*GraphStats_VertexDegree)(nil), // 9: GraphStats.VertexDegree
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_data_proto_depIdxs = []int32{
	10, // 0: Vertex.expiration:type_name -> google.protobuf.Timestamp
	10, // 1: Vertex.timestamp:type_name -> google.protobuf.Timestamp
	10, // 2: Edge.expiration:type_name -> google.protobuf.Timestamp
	9,  // 3: GraphStats.vertex_degrees:type_name -> GraphStats.VertexDegree
	1,  // 4: Graph.vertices:type_name -> Vertex
	2,  // 5: Graph.edges:type_name -> Edge
	3,  // 6: Graph.stats:type_name -> GraphStats
	4,  // 7: IlluminateResponse.graph:type_name -> Graph
	0,  // 8: IlluminateResponse.status:type_name -> Status
	0,  // 9: PutResponse.status:type_name -> Status
	5,  // 10: Lantern.Illuminate:input_type -> IlluminateRequest
	6,  // 11: Lantern.GetVertex:input_type -> Keys
	4,  // 12: Lantern.Put:input_type -> Graph
	4,  // 13: Lantern.PutVertex:input_type -> Graph
	4,  // 14: Lantern.PutEdge:input_type -> Graph
	7,  // 15: Lantern.Illuminate:output_type -> IlluminateResponse
	4,  // 16: Lantern.GetVertex:output_type -> Graph
	8,  // 17: Lantern.Put:output_type -> PutResponse
	8,  // 18: Lantern.PutVertex:output_type -> PutResponse
	8,  // 19: Lantern.PutEdge:output_type -> PutResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vertex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Edge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graph); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IlluminateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Keys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IlluminateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphStats_VertexDegree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_data_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Vertex_Float64)(nil),
		(*Vertex_Float32)(nil),
		(*Vertex_Int32)(nil),
		(*Vertex_Int64)(nil),
		(*Vertex_Uint32)(nil),
		(*Vertex_Uint64)(nil),
		(*Vertex_Bool)(nil),
		(*Vertex_String_)(nil),
		(*Vertex_Bytes)(nil),
		(*Vertex_Timestamp)(nil),
		(*Vertex_Nil)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		EnumInfos:         file_data_proto_enumTypes,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_rawDesc = nil
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
