name: Push to Docker registry

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN}}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t lantern .
          docker tag lantern ${{ DOCKER_USERNAME }}/lantern-server:${{ github.sha }}
          docker tag lantern ${{ DOCKER_USERNAME }}/lantern-server:latest-alpha

      - name: Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker push ${{ DOCKER_USERNAME }}/lantern-server:${{ github.sha }}
          docker push ${{ DOCKER_USERNAME }}/lantern-server:latest-alpha
